/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget *create_window1(void);
GtkWidget *create_dialog_taskentry(caltime_t *tod, int taskid);
GtkWidget *create_dialog_options(void);
GtkWidget *create_dialog_reminder(char *taskname, int procable);
GtkWidget *create_filechooserdialog1(void);
void errormsg(int sev, const char *msg, ...);
